spring.application.name=prestamos-service
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.datasource.url=jdbc:postgresql://localhost:5433/prestamosdb
spring.datasource.username=postgres
spring.datasource.password=2029
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


management.endpoints.web.exposure.include=*

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
